# Generated by Django 5.0.6 on 2024-06-22 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(choices=[('medecin_directeur', 'Medecin Directeur'), ('infirmier_titulaire', 'Infirmier Titulaire'), ('medecin', 'Médecin'), ('infirmier', 'Infirmier'), ('receptioniste', 'Réceptioniste'), ('pharmacien', 'Pharmacien'), ('laboratin', 'Laboratin'), ('stagiaire', 'Stagiaire'), ('medecin_visiteur', 'Médecin Visiteur')], max_length=50)),
                ('date_register', models.DateField(auto_now_add=True)),
                ('is_approuve', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AireDeSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nom')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'Aire de santé',
            },
        ),
        migrations.CreateModel(
            name='Clinical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom')),
                ('membership', models.CharField(choices=[('public', 'Publique'), ('private', 'Privé'), ('religious_confession', 'Confession réligieuse'), ('religious_confession_conventione', 'Confession réligieuse conventionée '), ('private_asbl', 'Privé Asbl')], max_length=128, verbose_name='Appartenance')),
                ('category', models.CharField(choices=[('hopital_general_de_reference', 'Hopital général de reference'), ('hopital_general', 'Hopital général'), ('hopital', 'Hopital'), ('centre_hospitalier', 'Centre hospitalier'), ('clinique_universitaire', 'Clinique_universitaire'), ('clinique', 'Clinique'), ('polyclinique', 'Polyclinique'), ('centre_medical', 'Centre medical'), ('centre_de_sante', 'Centre de santé'), ('centre_de_sante_de_reference', 'Centre de santé de reference'), ('centre_de_sante_universitaire', 'Centre de santé universitaire'), ('dispensaire', 'Dispensaire')], max_length=128, verbose_name='Catégorie')),
                ('zip_cod', models.CharField(max_length=16, unique=True, verbose_name='Code postal')),
                ('matricul', models.PositiveIntegerField(unique=True, verbose_name='matricule')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'Structure de santé',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom du service')),
            ],
            options={
                'verbose_name': 'Service',
            },
        ),
        migrations.CreateModel(
            name='ZoneDeSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='nom')),
                ('code_zone', models.CharField(max_length=50, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'Zone de santé',
            },
        ),
    ]
