# Generated by Django 5.0.6 on 2024-06-22 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinical',
            name='aire_de_sante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.airedesante'),
        ),
        migrations.AddField(
            model_name='clinical',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affectation',
            name='clinical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.clinical'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.service'),
        ),
        migrations.AddField(
            model_name='airedesante',
            name='health_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.zonedesante', verbose_name='zone de santé'),
        ),
    ]
