# Generated by Django 5.0.6 on 2024-07-28 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierEnvoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='dossiers/')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received')], default='sent', max_length=20)),
                ('receiver_clinical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_dossiers', to='clinical.clinical')),
                ('sender_clinical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_dossiers', to='clinical.clinical')),
            ],
        ),
    ]
