# Generated by Django 5.0.6 on 2024-06-22 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000)),
                ('post_nom', models.CharField(max_length=1000)),
                ('prenom', models.CharField(max_length=1000)),
                ('adresse', models.CharField(max_length=1000)),
                ('genre', models.CharField(choices=[('m', 'M'), ('f', 'F')], default='m', max_length=100)),
                ('date_birth', models.DateField()),
                ('code', models.CharField(blank=True, max_length=50)),
                ('date_register', models.DateField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('age_en_mois', models.IntegerField(blank=True, null=True)),
                ('age_en_annees', models.IntegerField(blank=True, null=True)),
                ('clinical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.clinical')),
            ],
        ),
        migrations.CreateModel(
            name='SSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tension', models.CharField(blank=True, max_length=20)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_register', models.DateField(auto_now_add=True)),
                ('clinical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.clinical')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
