# Generated by Django 5.0.6 on 2024-06-23 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_initial'),
        ('hospitalisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenPostHospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=255)),
                ('date_examen', models.DateField()),
                ('day_date', models.DateField(auto_now_add=True)),
                ('clinical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.clinical')),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalisation.hospitalisation')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentPostHospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=255)),
                ('posologie', models.CharField(max_length=255)),
                ('duree', models.CharField(max_length=255)),
                ('day_date', models.DateField(auto_now_add=True)),
                ('clinical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.clinical')),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalisation.hospitalisation')),
            ],
        ),
    ]
