# Generated by Django 5.0.6 on 2024-06-22 19:09

import user.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('poste', models.CharField(choices=[('medecin_chef_de_zone', 'Medecin Chef de zone'), ('medecin_chef_de_division_provincial', 'Medecin chef de Division Provincial'), ('medecin_chef_de_division_nationale', 'Medecin chef de Division National'), ('ministre_provincial', 'Ministre Provincial'), ('ministre_national', 'Ministre National'), ('infirmier_titulaire', 'Infirmier Titulaire'), ('administrateur', 'Administrateur'), ('administrateur_etablissement', 'Administrateur établissement'), ('medecin', 'Medecin'), ('infirmier', 'Infirmier'), ('pharmacien', 'Pharmacien'), ('laboratin', 'Laboratin')], default='administrateur_etablissement', max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=True, verbose_name='staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', user.managers.UserManager()),
            ],
        ),
    ]
