# Generated by Django 5.0.6 on 2024-06-23 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_initial'),
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='examens_demandes',
        ),
        migrations.CreateModel(
            name='ExamenDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_jour', models.DateField(auto_now_add=True)),
                ('clinical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.clinical')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_demandes', to='consultation.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentPrescrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('frequence', models.CharField(max_length=255)),
                ('duree', models.CharField(max_length=255)),
                ('date_jour', models.DateField(auto_now_add=True)),
                ('clinical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.clinical')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments_prescrits', to='consultation.consultation')),
            ],
        ),
    ]
