# Generated by Django 5.0.6 on 2024-06-23 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_remove_consultation_examens_demandes_examendemande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date_consultation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
